---
title: "NASA Space Apps Challenge"
author: "Swetha Natarajan"
date: '2022-10-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
```

```{r}
#install.packages("data.table")
library(data.table)
## this was just used to filter through some data sets, see what was there
## We don't really need this just keeping it on there 
GaiaData1 <- fread("GaiaSource_000-000-000.csv.gz")
View(GaiaData1)

##Main model and data we will be using
GaiaUnivModel <- fread("GaiaUniverseModel_4999.csv.gz")

# the radius given in the data set is in terms of solar radii. converting to earth radii.
GaiaUnivModel$earth_radius <- GaiaUnivModel$radius * 109.122

#metrics to look for: 
# Planet-star radius ratio, zero epoch, orbital period, scaled semi-major axis, inclination, eccentricity, argument of periastron, limb darkening coefficients
#this has everything but: zero epoch, limb darkening coefficients (necessary metrics)
GaiaUnivModel <- subset(GaiaUnivModel, select = c("source_id", "radial_velocity","spectral_type", "logg", "age", "radius", "vsini", "population", "semimajor_axis", "eccentricity", "orbit_period", "variability_period", "periastron_argument", "inclination", "mass", "earth_radius"))
View(GaiaUnivModel)

##There are some NA values in our data set, so we're going to remove them

#dropping NA values
testdataframe <- GaiaUnivModel %>% drop_na(earth_radius)

#getting range for slider
range(testdataframe$earth_radius)
#new range is : 5.978107e-01 4.370827e+04, also the same when tested in excel 

#exporting this as a CSV file
write.csv(GaiaUnivModel, "GaiaUnivModel1.csv", row.names = TRUE)

```


